### ISSUE TITLE
How to "Enable Information Protocol plugin"?

### ISSUE THREAD

**Issue by Kagukara** [soreau/wf-info#4]
I've looked everywhere on how to enable it and have come up with nothing. I must be missing something obvious if all that was said was to "Enable Information Protocol plugin".

I am using wayfire 0.7.4-1 from the aur and built wf-info using the instructions. I added wf-info to plugins in the wayfire.ini.

**Comment by soreau** [comment]
Adding `wf-info` to [core] plugins is the same as enabling Information Protocol (which is what it is called in wcm). You should be able to run `wf-info` from a terminal now that you've enabled the plugin. Does this help?

**Comment by Kagukara** [comment]
Ah, that's what I already had. running `wf-info` in the terminal outputs `Wayfire information protocol not advertised by compositor. Is wf-info plugin enabled?`.

**Comment by soreau** [comment]
The only dependency is wf-info plugin enabled in wayfire. Can you upload the log from wayfire? Maybe the plugin is not loading for some reason.

**Comment by Kagukara** [comment]
Here is the log file.
[log.txt](https://github.com/soreau/wf-info/files/9500420/log.txt)

**Comment by Kagukara** [comment]
Here is the log file for running `wf-info` in the terminal.
[log-wf-info.txt](https://github.com/soreau/wf-info/files/9500513/log-wf-info.txt)

**Comment by soreau** [comment]
Can you upload the output of `WAYLAND_DEBUG=1 wf-info`?

**Comment by Kagukara** [comment]
Text file for `WAYLAND_DEBUG=1 wf-info`.
[wf-info-debug.txt](https://github.com/soreau/wf-info/files/9500534/wf-info-debug.txt)

**Comment by soreau** [comment]
It's not advertising "wf_info_base" and I'm not sure why. The only difference I see is that you're using wayfire 0.7.4-1 and I'm using git, though I don't see any reason it shouldn't work with 0.7.4.

**Comment by Kagukara** [comment]
I have just switched to wayfire-git on the aur. `wayfire -v` outputs `0.8.0-da7a929c (Sep   6 2022, branch 'master'`

I have attached the log file for wayfire, wayfire+`wf-info` and `WAYLAND_DEBUG=1 wf-info` in case you see any changes that might help.

[log-aur-git.txt](https://github.com/soreau/wf-info/files/9501110/log-aur-git.txt)
[log-wf-info-aur-git.txt](https://github.com/soreau/wf-info/files/9501111/log-wf-info-aur-git.txt)
[wf-info-debug-aur-git.txt](https://github.com/soreau/wf-info/files/9501113/wf-info-debug-aur-git.txt)

I can remove the aur-git and try building it from the git hub if more data is needed to help solve the issue.

**Comment by soreau** [comment]
I notice the log says there are errors in the config file, maybe you need to fix those?

**Comment by Kagukara** [comment]
I commented out line 69 and it kept moving down. So when I rebooted it would say 70.

**Comment by Kagukara** [comment]
Here is my wayfire.ini file.

[wayfire.txt](https://github.com/soreau/wf-info/files/9501163/wayfire.txt)

**Comment by soreau** [comment]
Ah, I see the problem now. The `#` you have for wobbly is affecting wobbly and all the plugins listed thereafter. I can reproduce and when I remove the `#`, it works.

**Comment by Kagukara** [comment]
I was just about to say, yea removing the `#` fixed the error, but I still can't use wf-info.

[log-uncomment-wobbly.txt](https://github.com/soreau/wf-info/files/9501221/log-uncomment-wobbly.txt)

**Comment by soreau** [comment]
You need to rebuild wf-info (against wayfire git).

**Comment by Kagukara** [comment]
That has done the trick, it is now working. I guess I have to delete plugins I don't want instead of commenting them out.

[wf-info-working.txt](https://github.com/soreau/wf-info/files/9501242/wf-info-working.txt)

Thank you for the help.
